### ISSUE TITLE
sam: install fails if there is /root/[app_id] dir

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#135]
I had a dir /root/mail and ecause of that sam could not install mail app from the webui
I think we should have separate instal app_id and install --from-file app.zip so web can always use non-file based install

**Comment by cyberb** [comment]
IOError: [Errno 21] Is a directory: 'mail'
2016-03-22 07:48:01,870 - sam.manager - INFO - download filename: mail
2016-03-22 07:48:01,872 - sam.manager - INFO - filename: mail
2016-03-22 07:48:01,900 - app - ERROR - [Errno 21] Is a directory: 'mail'
Traceback (most recent call last):
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 38, in run
    data = runner()
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 58, in <lambda>
    run(lambda: call(method, vars(args)), args.debug, text, exit_code_on_error)
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 17, in call
    return func(**params)
  File "/opt/app/sam/lib/syncloud-sam-58/syncloud_sam/manager.py", line 142, in install
    self.__install(app_archive_filename, temp_dir)
  File "/opt/app/sam/lib/syncloud-sam-58/syncloud_sam/manager.py", line 145, in __install
    self.install_file(app_archive_filename)
  File "/opt/app/sam/lib/syncloud-sam-58/syncloud_sam/manager.py", line 170, in install_file
    tarfile.open(filename).extractall(unpack_dir)
  File "/opt/app/sam/python/lib/python2.7/tarfile.py", line 1667, in open
    return func(name, "r", fileobj, **kwargs)
  File "/opt/app/sam/python/lib/python2.7/tarfile.py", line 1732, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/opt/app/sam/python/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
