### ISSUE TITLE
Upgrade to ownCloud 9 failed, reinstall not possible

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#145]
ownCloud is v122

root@odroid-xu3and4:/opt/app/owncloud/bin# ./occ-runner upgrade
sudo: unable to resolve host odroid-xu3and4
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_preferences" SET "configvalue" = ? WHERE ("userid" = ?) AND ("appid" = ?) AND ("configkey" = ?)' with params ["syncloudtest", "syncloudtest", "user_ldap", "displayName"]:

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
Update failed
Maintenance mode is kept active
Reset log level
root@odroid-xu3and4:/opt/app/owncloud/bin#

**Comment by cyberb** [comment]
Could you send logs from Settings?
Just to see if it shows other problems.

**Comment by jpma89** [comment]
```
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.2.2 to 9.0.0.19","level":0,"time":"2016-04-20T05:26:48+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"getUsers: Options: search  limit 30 offset 0 Filter: (&(cn=*)(cn=*))","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter (&(cn=*)(cn=*)) base Array\n(\n    [0] => ou=users,dc=syncloud,dc=org\n)\n attr Array\n(\n    [0] => dn\n    [1] => uid\n    [2] => samaccountname\n    [3] => memberof\n    [4] => \n    [5] => \n    [6] => cn\n    [7] => \n)\n limit 30 offset 0","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=syncloudtest,ou=users,dc=syncloud,dc=org\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"Setting entryuuid as ldapUuidUserAttribute","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=syncloudtest,ou=users,dc=syncloud,dc=org\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=syncloudtest,ou=users,dc=syncloud,dc=org\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=syncloudtest,ou=users,dc=syncloud,dc=org\n)\n attr Array\n(\n    [0] => cn\n)\n limit 500 offset 0","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"user_ldap","message":"No DN found for syncloudtest on ldap:\/\/localhost","level":0,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
{"reqId":"OYD9eMvSRtVQu361Jj7j","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE \\\"oc_preferences\\\" SET \\\"configvalue\\\" = ? WHERE (\\\"userid\\\" = ?) AND (\\\"appid\\\" = ?) AND (\\\"configkey\\\" = ?)' with params [\\\"syncloudtest\\\", \\\"syncloudtest\\\", \\\"user_ldap\\\", \\\"displayName\\\"]:\\n\\nSQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE \\\"oc_pref...', Array)\\n#2 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE \\\"oc_pref...', Array, Array)\\n#3 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)\\n#4 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(294): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/allconfig.php(222): OC\\\\DB\\\\Connection->setValues('preferences', Array, Array, Array)\\n#7 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(368): OC\\\\AllConfig->setUserValue('syncloudtest', 'user_ldap', 'displayName', 'syncloudtest')\\n#8 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(383): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->store('displayName', 'syncloudtest')\\n#9 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(583): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->composeAndStoreDisplayName('syncloudtest', '')\\n#10 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/user\\\/user.php(187): OCA\\\\user_ldap\\\\lib\\\\Access->cacheUserDisplayName('syncloudtest', 'syncloudtest', '')\\n#11 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(732): OCA\\\\user_ldap\\\\lib\\\\user\\\\User->processAttributes(Array)\\n#12 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(705): OCA\\\\user_ldap\\\\lib\\\\Access->batchApplyUserAttributes(Array)\\n#13 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(192): OCA\\\\user_ldap\\\\lib\\\\Access->fetchListOfUsers('(&(cn=*)(cn=*))', Array, 30, 0)\\n#14 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(205): OCA\\\\user_ldap\\\\USER_LDAP->getUsers('', 30, 0)\\n#15 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair\\\/repairlegacystorages.php(214): OC\\\\User\\\\Manager->search('', 30, 0)\\n#16 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(86): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#17 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(341): OC\\\\Repair->run()\\n#18 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.19', '8.2.2.2')\\n#19 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/core\\\/command\\\/upgrade.php(225): OC\\\\Updater->upgrade()\\n#20 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#21 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#22 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#23 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#24 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#25 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#26 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/occ(11): require_once('\\\/opt\\\/app\\\/ownclo...')\\n#27 {main}\",\"File\":\"\\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91}","level":3,"time":"2016-04-20T05:27:54+00:00","method":"--","url":"--"}
```

**Comment by cyberb** [comment]
It is hard to say if this ldap message caused subsequent sql failure:

No DN found for syncloudtest on ldap

I am assuming you are using syncloudtest to login to Syncloud device and
ownCloud. I am not sure why ownCloud could not find it.

Can you logout and login to syncloud web to see if LDAP is working?

Also does ownCloud ask for user password before starting the upgrade?

We probably should run their upgrade procedure while upgrading our app so
it is more controlled and not bothering users with additional upgrade step.

If you need quick solution, you need to uninstall ownCloud and remove
/app/data/owncloud. Then install again. So there will be no upgrade, just
fresh latest ownCloud.

This is another thing we can fix, when users explicitly uninstall apps we
can remove user settings automatically (/app/data/[app])

**Comment by jpma89** [comment]
When I remove ownCloud using the webpage, /opt/appt/owncloud already gets removed:

''
root@odroid-xu3and4:/opt/app# ls
index  owncloud  platform  sam  versions
root@odroid-xu3and4:/opt/app# ls
index  platform  sam  versions
''

**Comment by jpma89** [comment]
Reinstallation after removing and logging in again brings up the ownCloud maintenance page.

**Comment by cyberb** [comment]
You need to remove /app/data/owncloud after uninstalling it. This dir
stores ownCloud database and settings, but not files. So it should be
removed to will get fresh version without the need of upgrading.
