### ISSUE TITLE
redirect: Can't delete user

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#154]
Most probably it's something to do with SPF records.

Anyway we should admin script to remove users manually from server (like send or unsubscribe tools). Such script would allow to test and reproduce problem that we have currently with user removal.

**Comment by vsapronov** [comment]
Logs from server:
[Sun Jun 05 12:42:22.427852 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/services.py", line 228, in user_domain_delete
[Sun Jun 05 12:42:22.427862 2016] [:error] [pid 18522]     self.dns.delete_domain(self.main_domain, domain)
[Sun Jun 05 12:42:22.427872 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/dns.py", line 55, in delete_domain
[Sun Jun 05 12:42:22.427882 2016] [:error] [pid 18522]     record = self.find_records(full_domain, 'SPF', identifier=None, all=False)
[Sun Jun 05 12:42:22.427891 2016] [:error] [pid 18522] AttributeError: Dns instance has no attribute 'find_records'
[Sun Jun 05 12:42:23.319723 2016] [:error] [pid 18522] ERROR:root:exception happened
[Sun Jun 05 12:42:23.319760 2016] [:error] [pid 18522] Traceback (most recent call last):
[Sun Jun 05 12:42:23.319770 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/services.py", line 228, in user_domain_delete
[Sun Jun 05 12:42:23.319780 2016] [:error] [pid 18522]     self.dns.delete_domain(self.main_domain, domain)
[Sun Jun 05 12:42:23.319790 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/dns.py", line 55, in delete_domain
[Sun Jun 05 12:42:23.319800 2016] [:error] [pid 18522]     record = self.find_records(full_domain, 'SPF', identifier=None, all=False)
[Sun Jun 05 12:42:23.319809 2016] [:error] [pid 18522] AttributeError: Dns instance has no attribute 'find_records'
[Sun Jun 05 12:42:28.637430 2016] [:error] [pid 18522] ERROR:root:exception happened
[Sun Jun 05 12:42:28.637463 2016] [:error] [pid 18522] Traceback (most recent call last):
[Sun Jun 05 12:42:28.637474 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/services.py", line 228, in user_domain_delete
[Sun Jun 05 12:42:28.637484 2016] [:error] [pid 18522]     self.dns.delete_domain(self.main_domain, domain)
[Sun Jun 05 12:42:28.637493 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/dns.py", line 48, in delete_domain
[Sun Jun 05 12:42:28.637502 2016] [:error] [pid 18522]     zone.delete_a(wildcard_domain)
[Sun Jun 05 12:42:28.637512 2016] [:error] [pid 18522]   File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 380, in delete_a
[Sun Jun 05 12:42:28.637521 2016] [:error] [pid 18522]     return self.delete_record(record)
[Sun Jun 05 12:42:28.637531 2016] [:error] [pid 18522]   File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 156, in delete_record
[Sun Jun 05 12:42:28.637540 2016] [:error] [pid 18522]     return Status(self.route53connection, self._commit(changes))
[Sun Jun 05 12:42:28.637549 2016] [:error] [pid 18522]   File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 59, in _commit
[Sun Jun 05 12:42:28.637559 2016] [:error] [pid 18522]     response = changes.commit()
[Sun Jun 05 12:42:28.637568 2016] [:error] [pid 18522]   File "/usr/local/lib/python2.7/dist-packages/boto/route53/record.py", line 165, in commit
[Sun Jun 05 12:42:28.637577 2016] [:error] [pid 18522]     return self.connection.change_rrsets(self.hosted_zone_id, self.to_xml())
[Sun Jun 05 12:42:28.637599 2016] [:error] [pid 18522]   File "/usr/local/lib/python2.7/dist-packages/boto/route53/record.py", line 155, in to_xml
[Sun Jun 05 12:42:28.637610 2016] [:error] [pid 18522]     changeParams = {"action": change[0], "record": change[1].to_xml()}
[Sun Jun 05 12:42:28.637619 2016] [:error] [pid 18522] AttributeError: 'NoneType' object has no attribute 'to_xml'
[Sun Jun 05 12:42:29.468696 2016] [:error] [pid 18522] ERROR:root:exception happened
[Sun Jun 05 12:42:29.468722 2016] [:error] [pid 18522] Traceback (most recent call last):
[Sun Jun 05 12:42:29.468732 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/services.py", line 228, in user_domain_delete
[Sun Jun 05 12:42:29.468745 2016] [:error] [pid 18522]     self.dns.delete_domain(self.main_domain, domain)
[Sun Jun 05 12:42:29.468754 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/dns.py", line 55, in delete_domain
[Sun Jun 05 12:42:29.468764 2016] [:error] [pid 18522]     record = self.find_records(full_domain, 'SPF', identifier=None, all=False)
[Sun Jun 05 12:42:29.468773 2016] [:error] [pid 18522] AttributeError: Dns instance has no attribute 'find_records'
[Sun Jun 05 12:42:36.092435 2016] [:error] [pid 18522] ERROR:root:exception happened
[Sun Jun 05 12:42:36.092471 2016] [:error] [pid 18522] Traceback (most recent call last):
[Sun Jun 05 12:42:36.092481 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/services.py", line 277, in do_delete_user
[Sun Jun 05 12:42:36.092490 2016] [:error] [pid 18522]     self.dns.delete_domain(self.main_domain, domain)
[Sun Jun 05 12:42:36.092500 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/dns.py", line 55, in delete_domain
[Sun Jun 05 12:42:36.092509 2016] [:error] [pid 18522]     record = self.find_records(full_domain, 'SPF', identifier=None, all=False)
[Sun Jun 05 12:42:36.092518 2016] [:error] [pid 18522] AttributeError: Dns instance has no attribute 'find_records'
[Sun Jun 05 12:45:51.023948 2016] [:error] [pid 18522] ERROR:root:exception happened
[Sun Jun 05 12:45:51.024010 2016] [:error] [pid 18522] Traceback (most recent call last):
[Sun Jun 05 12:45:51.024019 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/services.py", line 277, in do_delete_user
[Sun Jun 05 12:45:51.024028 2016] [:error] [pid 18522]     self.dns.delete_domain(self.main_domain, domain)
[Sun Jun 05 12:45:51.024036 2016] [:error] [pid 18522]   File "/var/www/redirect-prod/redirect/dns.py", line 55, in delete_domain
[Sun Jun 05 12:45:51.024044 2016] [:error] [pid 18522]     record = self.find_records(full_domain, 'SPF', identifier=None, all=False)
[Sun Jun 05 12:45:51.024052 2016] [:error] [pid 18522] AttributeError: Dns instance has no attribute 'find_records'

**Comment by vsapronov** [comment]
Fixed all problems with deleting domain and user.
Created tool bin/delete in redirect. The tool allows to delete domain or user from cmd of the server.
