### ISSUE TITLE
Something breaks app installation

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#205]
file: /var/log/sam.log

    return opener.retrieve(url, filename, reporthook, data)
  File "/opt/app/sam/python/lib/python2.7/urllib.py", line 273, in retrieve
    block = fp.read(bs)
  File "/opt/app/sam/python/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
error: [Errno 104] Connection reset by peer
2016-10-27 02:01:03,147 - sam.manager - INFO - install: files
2016-10-27 02:01:03,150 - sam.manager - INFO - download app_id: files
2016-10-27 02:01:03,166 - sam.manager - INFO - downloading: http://apps.syncloud.org/apps/files-40-armv7l.tar.gz
2016-10-27 02:11:53,473 - sam.manager - INFO - install filename: /tmp/sam/files-40-armv7l.tar.gz
2016-10-27 02:12:38,322 - sam.manager - INFO - remove app_id: files
2016-10-27 02:12:38,324 - sam.manager - INFO - /opt/app/platform/bin/run_hook /opt/app/files/bin/pre-remove
2016-10-27 02:12:44,899 - sam.manager - INFO - checking app config folder: /opt/data/platform
2016-10-27 02:12:50,111 - sam.manager - INFO - app data dir exists: /opt/data/platform
2016-10-27 02:12:50,113 - sam.manager - INFO - checking app config folder: /opt/data/platform
2016-10-27 02:12:50,116 - sam.manager - INFO - app data dir exists: /opt/data/platform
2016-10-27 02:12:50,118 - sam.manager - INFO - removing /opt/data/platform/webapps/files.server
2016-10-27 02:12:50,119 - sam.manager - INFO - reloading platform-nginx
2016-10-27 02:12:50,213 - sam.manager - ERROR - Traceback (most recent call last):
2016-10-27 02:12:50,215 - sam.manager - ERROR - File "/opt/app/platform/bin/../bin/run_hook.py", line 7, in <module>
2016-10-27 02:12:50,217 - sam.manager - ERROR - run_script(sys.argv[1])
2016-10-27 02:12:50,218 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/gaplib/scripts.py", line 4, in run_script
2016-10-27 02:12:50,220 - sam.manager - ERROR - execfile(script_filename, g)
2016-10-27 02:12:50,222 - sam.manager - ERROR - File "/opt/app/files/bin/pre-remove", line 13, in <module>
2016-10-27 02:12:50,224 - sam.manager - ERROR - app.unregister_web()
2016-10-27 02:12:50,227 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/application/appsetup.py", line 23, in unregister_web
2016-10-27 02:12:50,229 - sam.manager - ERROR - self.nginx.remove_app(self.app_name)
2016-10-27 02:12:50,233 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/control/nginx.py", line 35, in remove_app
2016-10-27 02:12:50,235 - sam.manager - ERROR - reload_service('platform-nginx')
2016-10-27 02:12:50,238 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/control/systemctl.py", line 17, in reload_service
2016-10-27 02:12:50,240 - sam.manager - ERROR - check_output('systemctl reload {0} 2>&1'.format(service), shell=True)
2016-10-27 02:12:50,242 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/subprocess.py", line 573, in check_output
2016-10-27 02:12:50,244 - sam.manager - ERROR - raise CalledProcessError(retcode, cmd, output=output)
2016-10-27 02:12:50,246 - sam.manager - ERROR - subprocess.CalledProcessError: Command 'systemctl reload platform-nginx 2>&1' returned non-zero exit status 1
2016-10-27 02:12:50,379 - sam.manager - ERROR - unable to run /opt/app/files/bin/pre-remove
2016-10-27 02:12:52,450 - sam.manager - INFO - files: removed successfully
2016-10-27 02:13:28,341 - sam.manager - INFO - /opt/app/platform/bin/run_hook /opt/app/files/bin/post-install
2016-10-27 02:13:34,249 - sam.manager - INFO - checking app config folder: /opt/data/platform
2016-10-27 02:13:34,251 - sam.manager - INFO - app data dir exists: /opt/data/platform
2016-10-27 02:13:34,253 - sam.manager - INFO - checking app config folder: /opt/data/platform
2016-10-27 02:13:34,256 - sam.manager - INFO - app data dir exists: /opt/data/platform
2016-10-27 02:13:34,258 - sam.manager - INFO - checking app config folder: /opt/data/files
2016-10-27 02:13:34,260 - sam.manager - INFO - app data dir exists: /opt/data/files
2016-10-27 02:13:34,261 - sam.manager - INFO - enabling files-uwsgi
2016-10-27 02:13:34,653 - sam.manager - INFO - starting files-uwsgi.service
2016-10-27 02:13:35,073 - sam.manager - INFO - enabling files-nginx
2016-10-27 02:13:35,374 - sam.manager - INFO - starting files-nginx.service
2016-10-27 02:13:35,419 - sam.manager - INFO - creating /opt/data/platform/webapps/files.server
2016-10-27 02:13:35,424 - sam.manager - INFO - reloading platform-nginx
2016-10-27 02:13:35,675 - sam.manager - ERROR - Traceback (most recent call last):
2016-10-27 02:13:35,677 - sam.manager - ERROR - File "/opt/app/platform/bin/../bin/run_hook.py", line 7, in <module>
2016-10-27 02:13:35,678 - sam.manager - ERROR - run_script(sys.argv[1])
2016-10-27 02:13:35,680 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/gaplib/scripts.py", line 4, in run_script
2016-10-27 02:13:35,682 - sam.manager - ERROR - execfile(script_filename, g)
2016-10-27 02:13:35,684 - sam.manager - ERROR - File "/opt/app/files/bin/post-install", line 54, in <module>
2016-10-27 02:13:35,686 - sam.manager - ERROR - app.register_web(1111)
2016-10-27 02:13:35,688 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/application/appsetup.py", line 20, in register_web
2016-10-27 02:13:35,690 - sam.manager - ERROR - self.nginx.add_app(self.app_name, port)
2016-10-27 02:13:35,692 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/control/nginx.py", line 22, in add_app
2016-10-27 02:13:35,693 - sam.manager - ERROR - reload_service('platform-nginx')
2016-10-27 02:13:35,696 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/control/systemctl.py", line 17, in reload_service
2016-10-27 02:13:35,698 - sam.manager - ERROR - check_output('systemctl reload {0} 2>&1'.format(service), shell=True)
2016-10-27 02:13:35,700 - sam.manager - ERROR - File "/opt/app/platform/python/lib/python2.7/subprocess.py", line 573, in check_output
2016-10-27 02:13:35,701 - sam.manager - ERROR - raise CalledProcessError(retcode, cmd, output=output)
2016-10-27 02:13:35,703 - sam.manager - ERROR - subprocess.CalledProcessError: Command 'systemctl reload platform-nginx 2>&1' returned non-zero exit status 1
2016-10-27 02:13:35,846 - app - ERROR - unable to run /opt/app/files/bin/post-install
Traceback (most recent call last):
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 38, in run
    data = runner()
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 58, in <lambda>
    run(lambda: call(method, vars(args)), args.debug, text, exit_code_on_error)
  File "/opt/app/sam/lib/syncloud-lib-2/syncloud_app/main.py", line 17, in call
    return func(**params)
  File "/opt/app/sam/lib/syncloud-sam-79/syncloud_sam/manager.py", line 196, in install
    self.install_file(app_archive_filename)
  File "/opt/app/sam/lib/syncloud-sam-79/syncloud_sam/manager.py", line 228, in install_file
    self.run_hook(app_id, 'post-install')
  File "/opt/app/sam/lib/syncloud-sam-79/syncloud_sam/manager.py", line 268, in run_hook
    raise Exception(message)
Exception: unable to run /opt/app/files/bin/post-install
2016-10-27 02:40:47,461 - sam.manager - INFO

**Comment by cyberb** [comment]
Will be different in Snapd.
