### ISSUE TITLE
Activate fails on invalid input symbol

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#212]
Traceback (most recent call last):
  File "/opt/app/platform/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app/platform/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/rest/internal.py", line 42, in activate
    main_domain
  File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/rest/facade/internal.py", line 18, in activate
    device_username, device_password, main_domain)
  File "/opt/app/platform/python/lib/python2.7/site-packages/syncloud_platform-962-py2.7.egg/syncloud_platform/device.py", line 42, in activate
    self.logger.info("activate {0}, {1}".format(user_domain, device_username))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 0: ordinal not in range(128)

**Comment by cyberb** [comment]
One user just reported that if login name contains ! (exclamation mark) symbol app authentication stops working (at least for Nextcloud)
