### ISSUE TITLE
[Nextcloud] Storage is temporarily not available

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#313]
When sharing from default user (LDAP) to a Nextcloud created user, sometimes shares are not accessible with this message: 'Storage is temporarily not available'

Server log:
````
Jul  5 07:26:52 odroid-xu3and4 odroid-xu3and4 nginx: 2018/07/05 07:26:52 [warn] 30901#0: *51712 an upstream response is buffered to a temporary file /opt/data/nextcloud/nginx/fastcgi_temp/0000000604 while reading upstream, client: unix:, server: localhost, request: "PROPFIND /remote.php/webdav/test HTTP/1.1", upstream: "fastcgi://unix:/opt/data/nextcloud/log/php5-fpm.sock:", host: "nextcloud.example.com"
Jul  5 07:26:53 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:26:53 +0000] "PROPFIND /remote.php/webdav/test HTTP/1.1" 207 3199644 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:26:56 odroid-xu3and4 slapd[30529]: conn=23033 op=7 UNBIND
Jul  5 07:26:56 odroid-xu3and4 slapd[30529]: conn=23033 fd=9 closed
Jul  5 07:26:59 odroid-xu3and4 slapd[30529]: conn=23034 fd=9 ACCEPT from IP=127.0.0.1:35870 (IP=127.0.0.1:389)
Jul  5 07:26:59 odroid-xu3and4 slapd[30529]: conn=23034 op=0 BIND dn="dc=example,dc=com" method=128
Jul  5 07:26:59 odroid-xu3and4 slapd[30529]: conn=23034 op=0 BIND dn="dc=example,dc=com" mech=SIMPLE ssf=0
Jul  5 07:26:59 odroid-xu3and4 slapd[30529]: conn=23034 op=0 RESULT tag=97 err=0 text=Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: get_filter: unknown filter type=48
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 op=1 SRCH base="cn=testuser,ou=users,dc=example,dc=com" scope=0 deref=0 filter="(?=undefined)"
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 op=1 SRCH attr=1.1
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: get_filter: unknown filter type=48
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 op=2 SRCH base="ou=users,dc=example,dc=com" scope=2 deref=0 filter="(?=undefined)"
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 op=2 SRCH attr=1.1
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 op=2 SEARCH RESULT tag=101 err=0 nentries=0 text=
Jul  5 07:27:00 odroid-xu3and4 ownCloud[3563]: {PHP} ldap_control_paged_result_response(): No server controls in result at /opt/app/nextcloud/nextcloud/apps/user_ldap/lib/LDAP.php#74
Jul  5 07:27:00 odroid-xu3and4 ownCloud[3563]: {files}  Backends provided no user object for testuser
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 op=3 UNBIND
Jul  5 07:27:00 odroid-xu3and4 slapd[30529]: conn=23034 fd=9 closed
Jul  5 07:27:00 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:00 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=test HTTP/1.1" 503 5364 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:16 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:16 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 330 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:19 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:19 +0000] "GET /apps/files/ HTTP/1.1" 200 5510 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:20 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:20 +0000] "GET /core/js/oc.js?v=a7ca15f9 HTTP/1.1" 200 3406 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:21 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:21 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 330 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:21 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:21 +0000] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:21 odroid-xu3and4 ownCloud[3563]: {files}  Backends provided no user object for testuser
Jul  5 07:27:21 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:21 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4993 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:21 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:21 +0000] "GET /apps/systemtags/lastused HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:21 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:21 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 199 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:21 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:21 +0000] "GET /apps/theming/img/core/filetypes/video.svg?v=0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:21 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:21 +0000] "GET /apps/theming/img/core/filetypes/application-pdf.svg?v=0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:25 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:25 +0000] "GET /apps/gallery/ HTTP/1.1" 200 3565 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:25 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:25 +0000] "GET /core/js/oc.js?v=a7ca15f9 HTTP/1.1" 200 3406 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:26 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:26 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 330 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:26 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:26 +0000] "GET /apps/gallery/config? HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:26 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:26 +0000] "GET /apps/gallery/slideshow HTTP/1.1" 200 392 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:27 odroid-xu3and4 ownCloud[3542]: {files}  Backends provided no user object for testuser
Jul  5 07:27:27 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:27 +0000] "GET /apps/gallery/files/list?location=&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bimage%2Fx-xbitmap%3Bimage%2Fbmp&features=&etag HTTP/1.1" 200 440 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:31 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:31 +0000] "GET /apps/gallery/thumbnails?ids=17223%3B17222%3B17221&scale=3&square=1&requesttoken=3%2BOyXEhJJhGwKNnyb7YiNJbn1TRin8Ag16spyH85Dus%3D%3AkrrKFhw8cV36W%2BzEDtJoW6XSlkMj%2FfNtpNIRjBNuSZg%3D HTTP/1.1" 200 762484 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:37 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:37 +0000] "GET /apps/gallery/ HTTP/1.1" 200 3566 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:37 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:37 +0000] "GET /core/js/oc.js?v=a7ca15f9 HTTP/1.1" 200 3406 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:38 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:38 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 330 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:38 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:38 +0000] "GET /apps/gallery/config? HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:38 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:38 +0000] "GET /apps/gallery/slideshow HTTP/1.1" 200 392 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:38 odroid-xu3and4 ownCloud[3563]: {files}  Backends provided no user object for testuser
Jul  5 07:27:38 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:38 +0000] "GET /apps/gallery/files/list?location=&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bimage%2Fx-xbitmap%3Bimage%2Fbmp&features=&etag HTTP/1.1" 200 440 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:39 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:39 +0000] "GET /apps/gallery/thumbnails?ids=17223%3B17222%3B17221&scale=3&square=1&requesttoken=rIdKWrUMf6UvKTU5wLX1J2JbaXzxl%2B%2BjSQJyAZ42G9g%3D%3A4d4yEOF5KOllWgAPodG%2FSFFuKguw9dzuOntKRfJhXKs%3D HTTP/1.1" 200 762484 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:39 odroid-xu3and4 rsyslogd-2007: action 'action 17' suspended, next retry is Thu Jul  5 07:29:09 2018 [try http://www.rsyslog.com/e/2007 ]
Jul  5 07:27:42 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:42 +0000] "GET /apps/files/ HTTP/1.1" 200 5498 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:43 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:43 +0000] "GET /core/js/oc.js?v=a7ca15f9 HTTP/1.1" 200 3406 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:43 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:43 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 330 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:44 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:44 +0000] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:44 odroid-xu3and4 ownCloud[3563]: {files}  Backends provided no user object for testuser
Jul  5 07:27:44 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:44 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4993 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:44 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:44 +0000] "GET /apps/systemtags/lastused HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:44 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:44 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 199 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
Jul  5 07:27:46 odroid-xu3and4 ownCloud[3563]: {files}  Backends provided no user object for testuser
Jul  5 07:27:46 odroid-xu3and4 ownCloud[3563]: {webdav} Exception: {"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Storage is temporarily not available","Code":0,"Trace":"#0 \/opt\/app\/nextcloud\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(967): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('test')\n#1 \/opt\/app\/nextcloud\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1666): Sabre\\DAV\\Server->getPropertiesIteratorForPath('test', Array, 1)\n#2 \/opt\/app\/nextcloud\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(355): Sabre\\DAV\\Server->generateMultiStatus(Object(Generator), false)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/opt\/app\/nextcloud\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/opt\/app\/nextcloud\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#6 \/opt\/app\/nextcloud\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/opt\/app\/nextcloud\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(80): Sabre\\DAV\\Server->exec()\n#8 \/opt\/app\/nextcloud\/nextcloud\/remote.php(164): require_once('\/opt\/app\/nextcl...')\n#9 {main}","File":"\/opt\/app\/nextcloud\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":163}
Jul  5 07:27:46 odroid-xu3and4 odroid-xu3and4 nginx: unix: - - [05/Jul/2018:07:27:46 +0000] "PROPFIND /remote.php/webdav/test HTTP/1.1" 503 249 "-" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36"
````

**Comment by cyberb** [comment]
Similar issue: https://github.com/nextcloud/server/issues/9220

**Comment by cyberb** [comment]
this may help it: https://github.com/syncloud/nextcloud/commit/a6e6d02f3e901391263957b73642c6b6df3abea2

**Comment by cyberb** [comment]
Fixed and published.
