### ISSUE TITLE
[android] Not allowed to start service Intent

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#318]
````
java.lang.RuntimeException: Unable to create application org.syncloud.android.SyncloudApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.syncloud.android/org.acra.sender.SenderService (has extras) }: app is in background uid UidRecord{ab9b8e7 u0a140 CEM  idle procs:1 seq(0,0,0)}
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6065)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.syncloud.android/org.acra.sender.SenderService (has extras) }: app is in background uid UidRecord{ab9b8e7 u0a140 CEM  idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
at android.app.ContextImpl.startService(ContextImpl.java:1484)
at android.content.ContextWrapper.startService(ContextWrapper.java:663)
at org.acra.sender.SenderServiceStarter.startService(SenderServiceStarter.java:36)
at org.acra.util.ApplicationStartupProcessor.sendApprovedReports(ApplicationStartupProcessor.java:76)
at org.acra.ACRA.init(ACRA.java:221)
at org.acra.ACRA.init(ACRA.java:150)
at org.acra.ACRA.init(ACRA.java:133)
at org.syncloud.android.SyncloudApplication.onCreate(SyncloudApplication.java:55)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
... 8 more
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.syncloud.android/org.acra.sender.SenderService (has extras) }: app is in background uid UidRecord{ab9b8e7 u0a140 CEM  idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
at android.app.ContextImpl.startService(ContextImpl.java:1484)
at android.content.ContextWrapper.startService(ContextWrapper.java:663)
at org.acra.sender.SenderServiceStarter.startService(SenderServiceStarter.java:36)
at org.acra.util.ApplicationStartupProcessor.sendApprovedReports(ApplicationStartupProcessor.java:76)
at org.acra.ACRA.init(ACRA.java:221)
at org.acra.ACRA.init(ACRA.java:150)
at org.acra.ACRA.init(ACRA.java:133)
at org.syncloud.android.SyncloudApplication.onCreate(SyncloudApplication.java:55)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
````

**Comment by cyberb** [comment]
Current workaround:
https://github.com/syncloud/platform/wiki/Device-activation

**Comment by cyberb** [comment]
Should be fixed by: https://github.com/syncloud/android/commit/ee19e02405419e9eb9945a64a8ae116c0d8b54ab
