### ISSUE TITLE
is activated error

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#330]
````
[pid: 613|app: 0|req: 61/90] 192.168.1.65 () {44 vars in 681 bytes} [Fri Oct  5 17:53:23 2018] GET /rest/installed_apps => generated 12 bytes in 10 msecs (HTTP/2.0 401) 3 headers in 246 bytes (1 switches on core 0)
------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/platform/180927694/python/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/snap/platform/180927694/python/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/snap/platform/180927694/python/lib/python2.7/site-packages/syncloud_platform-180927694-py2.7.egg/syncloud_platform/rest/flask_decorators.py", line 8, in new_func
    resp = make_response(f(*args, **kwargs))
  File "/snap/platform/180927694/python/lib/python2.7/site-packages/syncloud_platform-180927694-py2.7.egg/syncloud_platform/rest/flask_decorators.py", line 20, in new_func
    if not platform_user_config.is_activated():
  File "/snap/platform/180927694/python/lib/python2.7/site-packages/syncloud_platform-180927694-py2.7.egg/syncloud_platform/config/config.py", line 220, in is_activated
    return self.parser.getboolean('platform', 'activated')
  File "/snap/platform/180927694/python/lib/python2.7/ConfigParser.py", line 369, in getboolean
    if v.lower() not in self._boolean_states:
AttributeError: 'list' object has no attribute 'lower'
------------------------------------------------------------

````

**Comment by cyberb** [comment]
Migrated user config to sqlite db file to get some multi process isolation.
