### ISSUE TITLE
Syncthing is broken

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#396]
Unable to install:
````
root@amd64:~# snap install syncthing       error: cannot perform the following tasks: - Run install hook of "syncthing" snap if present (run hook "install":
-----
Traceback (most recent call last):
  File "/snap/syncthing/180918113/meta/hooks/install", line 6, in <module>
    from syncthing_hooks import SyncthingInstaller
  File "/snap/syncthing/180918113/hooks/syncthing_hooks.py", line 13, in <module>
    from syncloud_app import logger
ImportError: No module named syncloud_app
-----)
````

**Comment by cyberb** [comment]
Need to embed python to remove dependency on platform.

**Comment by cyberb** [comment]
Fixed and released
