### ISSUE TITLE
Bad gateway (missing certificate)

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#434]
````
2020-01-02 18:31:29,692 - path_checker - INFO - real link path: /opt/disk/external
2020-01-02 18:31:29,693 - path_checker - INFO - external disk path: /opt/disk/external
2020-01-02 18:31:29,693 - path_checker - INFO - link exists: True
Traceback (most recent call last):
  File "/snap/platform/191230132/meta/hooks/post-refresh", line 5, in <module>
    PlatformInstaller().post_refresh()
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-191230132-py2.7.egg/syncloud_platform/installer.py", line 84, in post_refresh
    self.init_services()
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-191230132-py2.7.egg/syncloud_platform/installer.py", line 59, in init_services
    injector.tls.init_certificate()
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-191230132-py2.7.egg/syncloud_platform/certificate/certificate_generator.py", line 164, in init_certificate
    self.platform_config.get_ssl_certificate_file())
  File "/snap/platform/current/python/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/snap/platform/current/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/var/snap/platform/common/syncloud.crt'
-----)
````

**Comment by cyberb** [comment]
If anyone encounter this problem, could you run this command:
````
ls -la /var/snap/platform/common/
````
And also could you send this file to support:

/var/snap/platform/common/log/platform.log

**Comment by cyberb** [comment]
This may have been related to broken certbot since Dec 20, 2019.
Fixed now.
