### ISSUE TITLE
Update 20041367 platform fails to start

### ISSUE THREAD

**Issue by marxistvegan** [syncloud/platform#489]
Update seemed to have run but now not able to start platform.

`root@syncloud:~# snap list
Name       Version    Rev        Tracking  Developer  Notes
nextcloud  200228131  200228131  stable    syncloud   -
pihole     191023246  191023246  stable    syncloud   -
platform   200225190  200225190  stable    syncloud   base
users      20011159   20011159   stable    syncloud   -
root@syncloud:~# snap restart platform
error: cannot perform the following tasks:
- restart of [platform.backend platform.nginx-api platform.nginx-internal platform.nginx-public platform.openldap platform.uwsgi-api platform.uwsgi-internal platform.uwsgi-public] (# systemctl restart snap.platform.backend.service snap.platform.nginx-api.service snap.platform.nginx-internal.service snap.platform.nginx-public.service snap.platform.openldap.service snap.platform.uwsgi-api.service snap.platform.uwsgi-internal.service snap.platform.uwsgi-public.service
Job for snap.platform.nginx-api.service failed. See 'systemctl status snap.platform.nginx-api.service' and 'journalctl -xn' for details.
Job for snap.platform.nginx-public.service failed. See 'systemctl status snap.platform.nginx-public.service' and 'journalctl -xn' for details.
Job for snap.platform.nginx-internal.service failed. See 'systemctl status snap.platform.nginx-internal.service' and 'journalctl -xn' for details.
Job for snap.platform.uwsgi-public.service failed. See 'systemctl status snap.platform.uwsgi-public.service' and 'journalctl -xn' for details.
Job for snap.platform.uwsgi-internal.service failed. See 'systemctl status snap.platform.uwsgi-internal.service' and 'journalctl -xn' for details.
Job for snap.platform.uwsgi-api.service failed. See 'systemctl status snap.platform.uwsgi-api.service' and 'journalctl -xn' for details.
)
- restart of [platform.backend platform.nginx-api platform.nginx-internal platform.nginx-public platform.openldap platform.uwsgi-api platform.uwsgi-internal platform.uwsgi-public] (exit status 1)
root@syncloud:~# 
`
and on snap refresh run I see this

`root@syncloud:~# snap refresh platform
error: cannot perform the following tasks:
- Run pre-refresh hook of "platform" snap if present (run hook "pre-refresh": 
-----
Traceback (most recent call last):
  File "/snap/platform/200225190/meta/hooks/pre-refresh", line 5, in <module>
    PlatformInstaller().pre_refresh()
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-200225190-py2.7.egg/syncloud_platform/installer.py", line 77, in pre_refresh
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-200225190-py2.7.egg/syncloud_platform/injector.py", line 43, in get_injector
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-200225190-py2.7.egg/syncloud_platform/injector.py", line 87, in __init__
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-200225190-py2.7.egg/syncloud_platform/rest/facade/internal.py", line 8, in __init__
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-200225190-py2.7.egg/syncloud_platform/config/config.py", line 48, in www_root_internal
  File "/snap/platform/current/python/lib/python2.7/site-packages/syncloud_platform-200225190-py2.7.egg/syncloud_platform/config/config.py", line 150, in __get
  File "/snap/platform/current/python/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'www_root_internal' in section: 'platform'
-----)
root@syncloud:~# 
`

**Comment by cyberb** [comment]
Did you upgrade from UI?

You still have old version somehow:
> platform 200225190 200225190 stable syncloud base

At this point you have new config and old code, which probably we should fix.
As a workaround try reinstalling.
```
snap remove platform
snap install platform
```
Then you will have to activate your device again.
