### ISSUE TITLE
events not working

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#515]
```
2020-05-30 21:55:50,259 - events - ERROR - event error: b''
2020-05-30 21:55:50,260 - events - ERROR - Traceback (most recent call last):
  File "/snap/platform/200516351/python/lib/python3.7/site-packages/syncloud_platform-200516351-py3.7.egg/syncloud_platform/events.py", line 25, in _trigger_app_event
    output = check_output('snap run {0}'.format(command), shell=True).decode()
  File "/snap/platform/200516351/python/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/snap/platform/200516351/python/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'snap run nextcloud.access-change' returned non-zero exit status 1.
```

**Comment by cyberb** [comment]
Fixed and released
