### ISSUE TITLE
diaspora console is not working

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#543]
````
root@syncloud:/snap/diaspora/current/diaspora# bundle exec rails console
/snap/diaspora/20043055/ruby/lib/ruby/2.4.0/irb/completion.rb:10:in `require': libreadline.so.6: cannot open shared object file: No such file or directory - /snap/diaspora/20043055/ruby/lib/ruby/2.4.0/x86_64-linux/readline.so (LoadError)
	from /snap/diaspora/20043055/ruby/lib/ruby/2.4.0/irb/completion.rb:10:in `<top (required)>'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:2:in `require'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:2:in `<top (required)>'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/behavior.rb:82:in `require'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/behavior.rb:82:in `block (2 levels) in lookup'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/behavior.rb:78:in `each'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/behavior.rb:78:in `block in lookup'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/behavior.rb:77:in `each'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command/behavior.rb:77:in `lookup'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command.rb:68:in `find_by_namespace'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/command.rb:42:in `invoke'
	from /snap/diaspora/20043055/diaspora/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
````

**Comment by cyberb** [comment]
please update diaspora and use updated console command:
```snap run diaspora.console```
