### ISSUE TITLE
[nextcloud] upgrade from 19.0.1 to 20.0.0 failed: ldap problems

### ISSUE THREAD

**Issue by flovl** [syncloud/platform#549]
Upgrade from nextcloud snap 200724171(Version 19.0.1) to 201013176(Version 20.0.0) failed.

> Command '/snap/nextcloud/current/bin/occ-runner ldap:set-config s01 ldapEmailAttribute mail' returned non-zero exit status 1

```
root@odroid-xu3and4:~# snap refresh nextcloud
error: cannot perform the following tasks:
- Run configure hook of "nextcloud" snap if present (run hook "configure":
-----
2020-10-26 20:45:22,216 - nextcloud_config - INFO - setting value: datadirectory = /opt/disk/external/nextcloud
2020-10-26 20:45:25,274 - nextcloud_config - INFO - setting datadirectory = /opt/disk/external/nextcloud
2020-10-26 20:45:28,408 - nextcloud_occ - INFO - Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
  - installed: true
  - version: 20.0.0.9
  - versionstring: 20.0.0
  - edition:
2020-10-26 20:45:29,725 - nextcloud_occ - INFO - Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode enabled
 Starting ...
    0/0 [>---------------------------]   0% Starting ...
    0/0 [->--------------------------]   0%2020-10-26 20:47:07,859 - nextcloud_occ - ERROR - occ error: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: keeweb
Disabled incompatible app: maps
Updating <accessibility> ...
Migrate old user config


Updated <accessibility> to 1.6.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.1.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.10.1
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.0.1
Updating <files_rightclick> ...
Updated <files_rightclick> to 0.17.0
Updating <logreader> ...
Updated <logreader> to 2.5.0
Updating <photos> ...
Updated <photos> to 1.2.0
Updating <privacy> ...
Updated <privacy> to 1.4.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.10.0
Updating <recommendations> ...
Updated <recommendations> to 0.8.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.10.0
Updating <settings> ...
Updated <settings> to 1.2.0
Updating <support> ...
Updated <support> to 1.3.0
Updating <survey_client> ...
Updated <survey_client> to 1.8.0
Updating <text> ...
Updated <text> to 3.1.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.9.0
Updating <viewer> ...
Updated <viewer> to 1.4.0
Updating <federation> ...
Updated <federation> to 1.10.1
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.8.0
Updating <oauth2> ...
Updated <oauth2> to 1.8.0
Updating <password_policy> ...
Updated <password_policy> to 1.10.1
Updating <user_ldap> ...
Updated <user_ldap> to 1.10.2
Updating <files> ...
Updated <files> to 1.15.0
Updating <activity> ...
Updated <activity> to 2.13.1
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.3.0
Updating <dav> ...
Fix broken values of calendar objects


Updated <dav> to 1.16.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.12.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.10.1
Updating <files_versions> ...
Updated <files_versions> to 1.13.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.10.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.2.0
Updating <comments> ...
Updated <comments> to 1.10.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.9.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.9.0
Updating <notifications> ...
Updated <notifications> to 2.8.0
Updating <systemtags> ...
Updated <systemtags> to 1.10.0
Updating <theming> ...
Updated <theming> to 1.11.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app contacts in appstore
Checked for update of app "contacts" in appstore
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app deck in appstore
Checked for update of app "deck" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app mail in appstore
Update app mail from appstore
An unhandled exception has been thrown:
Error: Class 'OCA\Mail\AppInfo\BootstrapSingleton' not found in /var/snap/nextcloud/201013176/extra-apps/mail/lib/AppInfo/Application.php:35
Stack trace:
#0 /snap/nextcloud/201013176/nextcloud/lib/private/ServerContainer.php(108): OCA\Mail\AppInfo\Application->__construct()
#1 /snap/nextcloud/201013176/nextcloud/lib/private/ServerContainer.php(171): OC\ServerContainer->getAppContainer('mail', 'Mail')
#2 /snap/nextcloud/201013176/nextcloud/lib/private/ServerContainer.php(138): OC\ServerContainer->getAppContainerForService('OCA\\Mail\\Migrat...')
#3 /snap/nextcloud/201013176/nextcloud/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query('OCA\\Mail\\Migrat...')
#4 /snap/nextcloud/201013176/nextcloud/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance('1050Date2020062...')
#5 /snap/nextcloud/201013176/nextcloud/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('1050Date2020062...', false)
#6 /snap/nextcloud/201013176/nextcloud/lib/private/legacy/OC_App.php(976): OC\DB\MigrationService->migrate()
#7 /snap/nextcloud/201013176/nextcloud/lib/private/Installer.php(206): OC_App::updateApp('mail')
#8 /snap/nextcloud/201013176/nextcloud/lib/private/Updater.php(452): OC\Installer->updateAppstoreApp('mail')
#9 /snap/nextcloud/201013176/nextcloud/lib/private/Updater.php(260): OC\Updater->upgradeAppStoreApps(Array)
#10 /snap/nextcloud/201013176/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.0.9', '19.0.1.1')
#11 /snap/nextcloud/201013176/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#12 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /snap/nextcloud/201013176/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /snap/nextcloud/201013176/nextcloud/console.php(100): OC\Console\Application->run()
#18 /snap/nextcloud/201013176/nextcloud/occ(11): require_once('/snap/nextcloud...')
#19 {main}
2020-10-26 20:47:07,859 - nextcloud_installer - WARNING - unable to upgrade
2020-10-26 20:47:07,860 - nextcloud_installer - WARNING - Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled incompatible app: keeweb
Disabled incompatible app: maps
Updating <accessibility> ...
Migrate old user config


Updated <accessibility> to 1.6.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.1.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.10.1
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.0.1
Updating <files_rightclick> ...
Updated <files_rightclick> to 0.17.0
Updating <logreader> ...
Updated <logreader> to 2.5.0
Updating <photos> ...
Updated <photos> to 1.2.0
Updating <privacy> ...
Updated <privacy> to 1.4.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.10.0
Updating <recommendations> ...
Updated <recommendations> to 0.8.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.10.0
Updating <settings> ...
Updated <settings> to 1.2.0
Updating <support> ...
Updated <support> to 1.3.0
Updating <survey_client> ...
Updated <survey_client> to 1.8.0
Updating <text> ...
Updated <text> to 3.1.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.9.0
Updating <viewer> ...
Updated <viewer> to 1.4.0
Updating <federation> ...
Updated <federation> to 1.10.1
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.8.0
Updating <oauth2> ...
Updated <oauth2> to 1.8.0
Updating <password_policy> ...
Updated <password_policy> to 1.10.1
Updating <user_ldap> ...
Updated <user_ldap> to 1.10.2
Updating <files> ...
Updated <files> to 1.15.0
Updating <activity> ...
Updated <activity> to 2.13.1
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.3.0
Updating <dav> ...
Fix broken values of calendar objects


Updated <dav> to 1.16.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.12.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.10.1
Updating <files_versions> ...
Updated <files_versions> to 1.13.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.10.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.2.0
Updating <comments> ...
Updated <comments> to 1.10.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.9.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.9.0
Updating <notifications> ...
Updated <notifications> to 2.8.0
Updating <systemtags> ...
Updated <systemtags> to 1.10.0
Updating <theming> ...
Updated <theming> to 1.11.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app contacts in appstore
Checked for update of app "contacts" in appstore
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app deck in appstore
Checked for update of app "deck" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app mail in appstore
Update app mail from appstore
An unhandled exception has been thrown:
Error: Class 'OCA\Mail\AppInfo\BootstrapSingleton' not found in /var/snap/nextcloud/201013176/extra-apps/mail/lib/AppInfo/Application.php:35
Stack trace:
#0 /snap/nextcloud/201013176/nextcloud/lib/private/ServerContainer.php(108): OCA\Mail\AppInfo\Application->__construct()
#1 /snap/nextcloud/201013176/nextcloud/lib/private/ServerContainer.php(171): OC\ServerContainer->getAppContainer('mail', 'Mail')
#2 /snap/nextcloud/201013176/nextcloud/lib/private/ServerContainer.php(138): OC\ServerContainer->getAppContainerForService('OCA\\Mail\\Migrat...')
#3 /snap/nextcloud/201013176/nextcloud/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query('OCA\\Mail\\Migrat...')
#4 /snap/nextcloud/201013176/nextcloud/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance('1050Date2020062...')
#5 /snap/nextcloud/201013176/nextcloud/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('1050Date2020062...', false)
#6 /snap/nextcloud/201013176/nextcloud/lib/private/legacy/OC_App.php(976): OC\DB\MigrationService->migrate()
#7 /snap/nextcloud/201013176/nextcloud/lib/private/Installer.php(206): OC_App::updateApp('mail')
#8 /snap/nextcloud/201013176/nextcloud/lib/private/Updater.php(452): OC\Installer->updateAppstoreApp('mail')
#9 /snap/nextcloud/201013176/nextcloud/lib/private/Updater.php(260): OC\Updater->upgradeAppStoreApps(Array)
#10 /snap/nextcloud/201013176/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.0.9', '19.0.1.1')
#11 /snap/nextcloud/201013176/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#12 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /snap/nextcloud/201013176/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /snap/nextcloud/201013176/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /snap/nextcloud/201013176/nextcloud/console.php(100): OC\Console\Application->run()
#18 /snap/nextcloud/201013176/nextcloud/occ(11): require_once('/snap/nextcloud...')
#19 {main}
2020-10-26 20:47:09,259 - nextcloud_occ - INFO - Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
2020-10-26 20:47:11,878 - nextcloud_occ - INFO - Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Done.
2020-10-26 20:47:14,457 - nextcloud_occ - INFO - Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Check columns of the comments table.
Done.


  There are no commands defined in the "ldap" namespace.


2020-10-26 20:47:15,871 - nextcloud_occ - ERROR - occ error: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Traceback (most recent call last):
  File "/snap/nextcloud/201013176/meta/hooks/configure", line 7, in <module>
    Installer().configure()
  File "/snap/nextcloud/201013176/hooks/installer.py", line 112, in configure
    self.occ.run('ldap:set-config s01 ldapEmailAttribute mail')
  File "/snap/nextcloud/201013176/hooks/octools.py", line 19, in run
    raise e
subprocess.CalledProcessError: Command '/snap/nextcloud/current/bin/occ-runner ldap:set-config s01 ldapEmailAttribute mail' returned non-zero exit status 1
-----)
```

**Comment by cyberb** [comment]
This looks like usual mail Nextcloud app problem:
`Update app mail from appstore`
Try to upgrade or remove it first.

**Comment by flovl** [comment]
Thanks for your help.
I only focused on the last error which was the ldap error. (lesson learned) 
I disabled the mail app and then it worked.

Here's what I did
- snap run nextcloud.occ app:list  
  - mail 1.4.1
- snap run nextcloud.occ app:update mail
- snap run nextcloud.occ app:list  
  - mail 1.4.1 ... nothing happend with the version
- snap run nextcloud.occ app:disable mail 
  - can also be done via the browser interface 
- snap refresh nextcloud
  - upgrade without error
- snap run nextcloud.occ app:list
  - mail 1.5.1
